### ISSUE TITLE
Delayed code review for initial commit

### ISSUE THREAD

**Issue by alexasselin008** [workleap/wl-squide#1]
> wl-squide/packages/core/package.json

This package should have sideEffect:false to properly treeshake

> tsup.build.js
> tsup.build.js

They should be .ts files

> wl-squide/packages/react-router/package.json

This package should have sideEffect:false to properly treeshake

> wl-squide/packages/core/src/federation/useHoistedRoutes.ts

should be .tsx since its a react hook

> wl-squide/packages/react-router/package.json
```
"repository": {
 "directory": "core"
```

The directory is invalid, should be "packages/react-router"

> wl-squide/packages/core/package.json

```
"repository": {
 "directory": "core"
```

The directory is invalid, should be "packages/core"

> npm-run-all

It brings 9 new dependencies to the project. Is it really worth it for the use cases you have?  

For similar commands you can do : 
`pnpm run "/^watch:.*/"`

for different command you can do
`pnpm clean && pnpm reset:modules`

Adding npm-run-all is a new tool to install, and a new tool to learn for a new maintainer. 

> https://github.com/workleap/wl-squide/blob/main/package.json

jest is missing from the dev dependencies (i noticed because you added @types/jest but not jest"

> wl-squide

Squid is written without a e at the end :)

**Comment by alexasselin008** [comment]
Also, ideally next commit contains a github workflow that lints/run tests so we know the repo is ok

**Comment by patricklafrance** [comment]
> This package should have sideEffect:false to properly treeshake

✔️ Yes already added for both packages after the commit

> tsup.build.js
> tsup.build.js
> 
> They should be .ts files

✔️ interesting, first project that I work with supporting `.ts` config file without requiring to previously transpiled them

> wl-squide/packages/react-router/package.json
> 
> "repository": {
>  "directory": "core"
> The directory is invalid, should be "packages/react-router"
> 
> wl-squide/packages/core/package.json
> 
> "repository": {
>  "directory": "core"
> The directory is invalid, should be "packages/core"

✔️

> npm-run-all
> 
> It brings 9 new dependencies to the project. Is it really worth it for the use cases you have?
> 
> For similar commands you can do :
> pnpm run "/^watch:.*/"
> 
> for different command you can do
> pnpm clean && pnpm reset:modules
> 
> Adding npm-run-all is a new tool to install, and a new tool to learn for a new maintainer.

I can remove it for now but my guess is that it will probably come back at some point as both `pnpm` with a regex and the `&&` operator doesn't cover every cross platform usecases.

Also far as I know, [`pnpm` still recommand using `npm-run-all`](https://github.com/pnpm/pnpm/issues/2846#issuecomment-691662898). Do you have additional information suggesting otherwise? This issue is 3 years old but I haven't been able to find any relevant information suggesting that `pnpm` are now suggesting otherwise.

> jest is missing from the dev dependencies (i noticed because you added @types/jest but not jest"

✔️ Moved `@types/jest` to the `core` project and also added `jest`

**Comment by patricklafrance** [comment]
Forgot this one

> wl-squide/packages/core/src/federation/useHoistedRoutes.ts
> 
> should be .tsx since its a react hook

There's no JSX in the file so there's no need to use a `.tsx` file extension,

**Comment by alexasselin008** [comment]
Most pnpm repos i've seen use a build system in addition to pnpm, and they come with ways to handle running multiple commands built in

**Comment by alexasselin008** [comment]
> Forgot this one:
> 
> > wl-squide/packages/core/src/federation/useHoistedRoutes.ts
> > should be .tsx since its a react hook
> 
> There's no JSX in the file so there's no need to use a `.tsx` file extension.

I guess you're right! Always tought the extension was if i imported React, but its related to having JSX in it

**Comment by patricklafrance** [comment]
> > I can remove it for now but my guess is that it will probably come back at some point as both pnpm with a regex and the && operator doesn't cover every cross platform usecases and using a regex is not always convenient compared to npm-run-all syntax.
> > Also, as far as I know, [pnpm/pnpm#2846 (comment)](https://github.com/pnpm/pnpm/issues/2846#issuecomment-691662898). Do you have additional information suggesting otherwise? This issue is 3 years old but I haven't been able to find any relevant information suggesting that pnpm are now suggesting otherwise.
> 
> Most pnpm repos i've seen use a build system in addition to pnpm, and they come with ways to handle running multiple commands built in
> 
> https://nx.dev/packages/nx/documents/run-many https://turbo.build/repo/docs/reference/command-line-reference#turbo-run-task

Not sure about `run` from Turbo but regarding Nx `run-many` it's purpose seems to be to run a task on multiple projects which is not exactly what `npm-run-all` does. The last example of `run-many` seems to showcases how to run multiple tasks but it's quite complicated relative to `npm-run-all`.

Anyway, adding a build system really depends if the project has performance issues and requires adding a cache layer on top of the workspace manager. If it's not the case I would rather add `npm-run-all` than Turbo or Nx as it takes about 5 minutes to learn and master while these build system takes days to understand.
